name: PR Checks

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install
        run: |
          python -m pip install -r requirements.txt
          pip install -e .
      - name: Validate PR title
        run: |
          echo "Validating PR title..."
          git-pr-helper validate --title "${{ github.event.pull_request.title }}" --body-file pr_body.md || exit 1
